Fix #3266 - corrige boot gunicorn
interlegis/sapl pull request #3267
Opened 2020-09-10 18:47 UTC by puera

## Descrição
Corrige boot gunicorn

## _Issue_ Relacionada
#3266 

## Tipos de Mudanças

- [X] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes)
- [ ] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes)
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes)

## Checklist:

- [X] Eu li o documento de Contribuição (**CONTRIBUTING**).
- [X] Meu código segue o estilo de código deste projeto.
- [ ] Minha alteração requer uma alteração na documentação.
- [ ] Eu atualizei a documentação de acordo.
- [ ] Eu adicionei testes para cobrir minhas mudanças.
- [ ] Todos os testes novos e existentes passaram.

2020-09-11 15:25 UTC, edwardoliveira requested changes

2020-09-11 15:25 UTC, edwardoliveira commented on gunicorn_start.sh
> +source /var/interlegis/.virtualenvs/sapl/bin/activate
EU aconselharia a ter esse path base (/var/interlegis/.virtualenvs/sapl) como variável de ambiente. Se não definido, ele chama esse valor default mesmo. Na minha máquina, por exemplo, não esse caminho fica em $HOME/.virtualenvs/sapl

2020-09-21 15:58 UTC, edwardoliveira commented on gunicorn_start.sh
> +if [ "$SAPL_VIRTUAL_ENV" ]
```suggestion
SAPL_VENV_DIR=${SAPL_VIRTUAL_ENV-/var/interlegis/.virtualenvs/sapl}
```

2020-09-21 15:58 UTC, edwardoliveira commented on gunicorn_start.sh
> +if [ "$SAPL_VIRTUAL_ENV" ]
Isso substitui as linhas 33-38

2020-09-21 15:59 UTC, edwardoliveira commented on sapl/.env.example
> +DATABASE_URL=postgresql://postgres:@sapldb:/sapl
Esse arquivo é necessário?

2020-09-22 13:54 UTC, puera commented
Edward você está vendo o commit anterior, já fiz a alteração de substituição das linhas 33-38

2020-09-22 14:33 UTC, edwardoliveira commented
Certo. Fizemos uma reorganização dos arquivos relativos ao Docker aqui e agora eles estão todos dentro da pasta docker, incluindo o gunicorn_start.sh. Será necessário adaptar esse PR pra esse novo layout.

2020-09-23 18:58 UTC, puera commented
@edwardoliveira estava testando aqui o que foi sugerido e está dando erro, você quer que eu mande da forma que você propôs mesmo assim? o deixa da forma que funcionou anteriormente? assim eu já mando o commit com o layout atualizado

2020-10-02 17:31 UTC, edwardoliveira commented
@puera *Quaisquer* arquivos referentes ao docker deverão ficar agora na pasta docker. Estando nesta pasta pode ficar do jeito que funcionava antes.

2020-11-06 00:13 UTC, closed without merging

2020-12-18 21:05 UTC, puera commented
@edwardoliveira refiz a issue e a PR lá para os scripts para não ter conflitos com scripts do docker, desculpa a demora para refazer a PR, estava afastado por problemas de saúde