Adiciona Cargo para Bloco Parlamentar
interlegis/sapl pull request #3284
Opened 2020-10-01 13:53 UTC by cantuariavc

## Descrição

## _Issue_ Relacionada

Fix #3276 

## Como Isso Foi Testado?

Manualmente.

## Capturas de Tela (se apropriado):

![Captura de Tela 2020-10-01 às 10 47 01](https://user-images.githubusercontent.com/21143590/94817552-820ffa00-03d3-11eb-97fa-4968b0ef82ad.png)
![Captura de Tela 2020-10-01 às 10 47 03](https://user-images.githubusercontent.com/21143590/94817562-83412700-03d3-11eb-9239-3d0f0a536edf.png)

## Tipos de Mudanças

- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes)
- [ ] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes)
- [x] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes)

2020-10-02 17:08 UTC, edwardoliveira requested changes
Necessárias algumas mudanças.

2020-10-02 17:08 UTC, edwardoliveira commented on sapl/parlamentares/forms.py
> +            bloco_parlamentar = BlocoParlamentar.objects.filter(bloco=cd['bloco'], cargo=cd['cargo'])
Vc não poderia fazer essa lógica simplesmente colocando um `exclude(self.instance.pk)` na linha 679 e depois verificando se já existe? 

Isso tornaria desnecessária as linhas 680-681

2020-10-02 17:08 UTC, edwardoliveira commented on sapl/parlamentares/models.py
> +class BlocoParlamentar(models.Model):
Eu colocaria on nome desse model como `MembroBloco` ou pq o Bloco é bloco parlamentar, e tanto `BlocoParlamentar` quanto `ParlamentarBloco` são confusos nesses caso.

2020-10-05 10:21 UTC, cantuariavc commented on sapl/parlamentares/models.py
> +class BlocoParlamentar(models.Model):
fcc7e567c3ef28375a01ce466d1a3c37bca3f834

2020-10-05 10:57 UTC, cantuariavc commented on sapl/parlamentares/forms.py
> +            bloco_parlamentar = BlocoParlamentar.objects.filter(bloco=cd['bloco'], cargo=cd['cargo'])
Troquei por essa lógica:
```
if cd['cargo'].cargo_unico and BlocoMembro.objects.filter(bloco=cd['bloco'], cargo=cd['cargo'], data_saida__isnull=True).exclude(pk=self.instance.pk).exists():
            raise ValidationError(_("Cargo único já ocupado por outro membro."))
```

2020-10-05 12:53 UTC, edwardoliveira commented on sapl/parlamentares/models.py
> +        max_length=80,
Vamos aumentar o tamanho desse nome pra 120

2020-10-05 12:54 UTC, edwardoliveira commented on sapl/parlamentares/models.py
> +        max_length=80,
Aumentar pra uns 120

2020-10-05 12:59 UTC, edwardoliveira commented on sapl/parlamentares/forms.py
> +        print(BlocoMembro.objects.filter(bloco=cd['bloco'], cargo=cd['cargo']))
Esse print aqui tá sobrando.

2020-10-05 13:00 UTC, edwardoliveira commented on sapl/parlamentares/forms.py
> +                and BlocoMembro.objects.filter(bloco=cd['bloco'], cargo=cd['cargo'], data_saida__isnull=True)\
Colocar o `exists()` nesse filter.

2020-10-05 13:02 UTC, cantuariavc commented on sapl/parlamentares/forms.py
> +                and BlocoMembro.objects.filter(bloco=cd['bloco'], cargo=cd['cargo'], data_saida__isnull=True)\
Já tem na linha 682.
```
        if cd['cargo'].cargo_unico \
                and BlocoMembro.objects.filter(bloco=cd['bloco'], cargo=cd['cargo'], data_saida__isnull=True)\
                                       .exclude(pk=self.instance.pk).exists():
```

2020-10-05 13:03 UTC, cantuariavc commented on sapl/parlamentares/models.py
> +        max_length=80,
132e6f7e0299a621ad3897e1331e2687bc443ca1

2020-10-05 13:03 UTC, cantuariavc commented on sapl/parlamentares/models.py
> +        max_length=80,
132e6f7e0299a621ad3897e1331e2687bc443ca1

2020-10-05 13:06 UTC, cantuariavc commented on sapl/parlamentares/forms.py
> +        print(BlocoMembro.objects.filter(bloco=cd['bloco'], cargo=cd['cargo']))
3c6845e21d6a17f6372b655e300b4e0897f0d96f

2020-10-08 11:52 UTC, rjoao approved these changes

2020-12-21 16:01 UTC, merged