Corrige recuperação de Sessões Legislativa
interlegis/sapl pull request #3288
Opened 2020-10-07 14:09 UTC by cantuariavc

## Como Isso Foi Testado?

Manualmente.

## Capturas de Tela (se apropriado):

**Antes**
![Captura de Tela 2020-10-07 às 09 50 00](https://user-images.githubusercontent.com/21143590/95342130-73bb5580-088d-11eb-8805-144af3d4ec04.png)
**Depois**
![Captura de Tela 2020-10-07 às 11 01 07](https://user-images.githubusercontent.com/21143590/95342137-75851900-088d-11eb-9e24-60e01e1aed07.png)

## Tipos de Mudanças

- [x] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes)
- [ ] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes)
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes)

2020-10-07 15:03 UTC, edwardoliveira requested changes
Algumas alterações menores

2020-10-07 15:08 UTC, edwardoliveira commented on sapl/parlamentares/views.py
> +    cargos_ocupados = [(m.cargo.id, m.cargo.__str__()) for m in composicao_mesa]
```suggestion
    cargos_ocupados = composicao_mesa.values_list('cargo', 'cargo__descricao')

2020-10-07 15:09 UTC, edwardoliveira commented on sapl/parlamentares/views.py
> +    parlamentares_ocupados = [(m.parlamentar.id, m.parlamentar.__str__()) for m in composicao_mesa]
```suggestion
    parlamentares_ocupados = composicao_mesa.values_list('parlamentar', 'parlamentar__nome_parlamentar')
```

2020-10-07 15:15 UTC, edwardoliveira commented on sapl/parlamentares/views.py
> +    legislatura = request.GET.get('legislatura', Legislatura.objects.all().order_by('-data_inicio').first())
```suggestion
    legislatura = request.GET.get('legislatura', Legislatura.objects.order_by('-data_inicio').first())
```

2020-10-07 15:17 UTC, edwardoliveira commented on sapl/parlamentares/views.py
> +    sessoes = SessaoLegislativa.objects.filter(legislatura=legislatura, tipo='O').order_by('-data_inicio')
```suggestion
legislatura.sessaoplenaria_set.filter(tipo='0').order_by('-data_inicio')
```

2020-10-07 15:18 UTC, edwardoliveira commented on sapl/parlamentares/views.py
> +    sessoes = SessaoLegislativa.objects.filter(legislatura=legislatura, tipo='O').order_by('-data_inicio')
O tipo é zero ou 'O'?

2020-10-07 15:19 UTC, edwardoliveira submitted a review, later dismissed
Algumas mudanças a serem realizadas.

2020-10-08 10:49 UTC, cantuariavc commented on sapl/parlamentares/views.py
> +    sessoes = SessaoLegislativa.objects.filter(legislatura=legislatura, tipo='O').order_by('-data_inicio')
O de ordinária.

2020-10-13 14:04 UTC, cantuariavc commented on sapl/parlamentares/views.py
> +    legislatura.sessaoplenaria_set.filter(tipo='O').order_by('-data_inicio')
```suggestion
    sessoes = legislatura.sessaoplenaria_set.filter(tipo='O').order_by('-data_inicio')
```

2020-10-13 14:08 UTC, edwardoliveira approved these changes
LGTM

2020-10-13 14:08 UTC, merged