Permite exibição do voto no painel com votação ainda aberta
interlegis/sapl pull request #3615
Opened 2022-10-06 17:01 UTC by cristian-longhi

## Descrição

No menu Sistema -> Tabelas Auxiliares -> Configurações da Aplicação, Módulo Painel, foi inserido um checklist para opção de exibir ou não o voto informado pelo Parlamentar no momento em que é registrado, ou seja, antes do encerramento da votação.
O valor padrão é não marcado ("False" no banco de dados), situação em que é mantido o comportamento atual do painel - altera a cor do nome do Parlamentar para amarelo quando o voto foi informado, porém a exibição dos votos somente após o fechamento da votação.
 
## _Issue_ Relacionada

#3593

## Motivação e Contexto

A issue relacionada refere-se à situação atual da votação como se fosse secreta, em função de não mostrar os votos imediatamente. Discordo desse conceito de que a votação seja ou secreta ou "quase secreta" da forma como está implementada -- pelo menos em nosso Regimento Interno a votação secreta tem contexto, aplicação e método diferentes. Entendo, no entanto, que algumas Casas Legislativas tenham a preferência por essa forma mais imediata de exibição do voto. Assim sendo, essa implementação dá ao Operador do SAPL a opção de escolha pelo formato que melhor convier.

## Como Isso Foi Testado?

Manualmente.

## Capturas de Tela (se apropriado):

Módulo Painel nas Configurações da Aplicação com a opção de exibição dos votos:
![image](https://user-images.githubusercontent.com/22030378/194372731-798b6e57-e901-4b4a-bebe-e84a0aaecd56.png)

Situação intermediária do painel - votação aberta. Matéria com situação "Ainda não foi votada." e tendo 1 voto informado:
![image](https://user-images.githubusercontent.com/22030378/194373341-cdb31382-8d9d-4746-afba-7fa997ded7b0.png)

## Tipos de Mudanças

- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes)
- [X] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes)
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes)

## Checklist:

- [ ] Eu li o documento de Contribuição (**CONTRIBUTING**).
- [X] Meu código segue o estilo de código deste projeto.
- [X] Minha alteração requer uma alteração na documentação.
- [ ] Eu atualizei a documentação de acordo.
- [ ] Eu adicionei testes para cobrir minhas mudanças.
- [ ] Todos os testes novos e existentes passaram.

2022-10-13 14:13 UTC, edwardoliveira commented
Olá, obrigado pelo PR! E pelos outros também. Iremos analisar todos e fornecer feedback para possibilitar o merge. Mil desculpas pela demora. 

Acerca deste PR, não creio que seja necessário uma `flag` pra mostrar ou não ou voto antes do fim da votação. Não lembro de nenhum requisito que exija que os votos só sejam mostrados depois de fechada a votação. Isso é uma limitação do SAPL mesmo, de quem implementou isso na época. Desta forma, acho que podemos estabelecer que os votos sempre estarão visíveis mesmo antes da votação fechada. Isso trará mais transparência ao processo de votação, conforme solicitado por algumas casas.

2022-10-13 14:13 UTC, edwardoliveira requested changes

2022-10-13 14:13 UTC, edwardoliveira commented on sapl/base/migrations/0055_appconfig_mostrar_voto.py
> +    ]
Retirar essa migration.

2022-10-13 14:13 UTC, edwardoliveira commented on sapl/base/forms.py
> +
Retirar esse campo. Sempre exibir os votos com a votação ainda aberta.

2022-10-13 14:13 UTC, edwardoliveira commented on sapl/base/models.py
> +
Remover.

2022-10-13 14:13 UTC, edwardoliveira commented on sapl/painel/views.py
> +def get_votos(response, materia, mostrar_voto):
Remover.

2022-10-13 14:13 UTC, edwardoliveira commented on sapl/painel/views.py
> +                            response['presentes'][i]['voto'] = 'Voto Informado'
```suggestion
                    if voto:
                            response['presentes'][i]['voto'] = voto
```

2022-10-13 14:13 UTC, edwardoliveira commented on sapl/painel/views.py
> +        'mostrar_voto': app_config.mostrar_voto
Remover.

2022-10-13 14:13 UTC, edwardoliveira commented on sapl/painel/views.py
> +            ordem_dia, app_config.mostrar_voto))
Desfazer

2022-10-13 14:13 UTC, edwardoliveira commented on sapl/painel/views.py
> +            expediente, app_config.mostrar_voto))
Desfazer.

2022-10-13 14:13 UTC, edwardoliveira commented on sapl/painel/views.py
> +                            ordem_expediente, app_config.mostrar_voto))
Desfazer

2022-10-13 14:13 UTC, edwardoliveira commented on sapl/templates/base/layouts.yaml
> +  - mostrar_brasao_painel mostrar_voto
Desfazer

2022-10-13 14:13 UTC, edwardoliveira commented on sapl/templates/painel/index.html
> +                    if (parlamentar.voto == 'Voto Informado' && mostrar_voto == false){
Desfazer.

2022-10-13 16:40 UTC, cristian-longhi commented
Acho importante podermos manter a escolha da forma de exibição a critério do operador. Os Regimentos Internos das Casas são os mais variados possíveis, e não se pode garantir que há ou haverá em algum deles um dispositivo contrário a esse comportamento. Entendo que a exibição de todos os votos no mesmo momento gera uma "isonomia" entre os Parlamentares, exibindo todos os votos pelo mesmo período.
Além disso, essa forma de exibição pode gerar alguns incovenientes operacionais, como o Parlamentar selecionar o voto trocado e ter de alterar, e essa alteração será exibida também. As votações também tendem a demorar mais, sobretudo quando forem matérias polêmicas.
Outra situação é que, sem poder escolher, estaríamos obrigando todas as Casas que usam o painel hoje a alterar a sistemática repentinamente, o que pode causar transtornos.
Faço essas ponderações após consulta ao setor legislativo aqui da Casa que mostrou preferência pela sistemática atual e apontou algumas das situações elencadas. Além disso, acreditamos  que o modo atual não compromete a transparência do processo, já que os votos são exibidos, e o fato de ter a opção pode incentivar a utilização do SAPL por Casas que ainda não o fazem.

2022-10-14 13:39 UTC, ARTEMIOFRIEDRICH commented
Como colaborador/sugestor/testador (rsrs) de diversas implementações/melhorias no SAPL (que defendo arduamente!), sempre em parceria com nossa valorosa e qualificada equipe de TI da CMNH) gostaria de reforçar que entendo importante a disponibilização de um "flag" que permita ao Operador (cfe. dinâmica de cada Casa Legislativa) definir a exibição OU não do voto antes do final da votação. Isso porque, Regimentalmente (assim como nós aqui, acredito que possa ter outras situações), onde para votação NOMINAL temos que seguir em estrita ORDEM ALFABÉTICA, o que inviabilizaria a votação eletrônica atualmente implementada, pois teria que ser feito alteração que permitisse por exemplo que o vereador B só pudesse votar após o vereador A ... Portanto, ter FLAG seria a solução mais adequada globalmente (fica opcional a quem quiser/puder usar regimentalmente e não cria problemas aos que não tem no momento condição regimental/decisória para tal). obg

2022-10-20 13:05 UTC, edwardoliveira commented
Tudo bem, podemos deixar o parâmetro.

2022-10-20 13:05 UTC, merged