feat: nova funcionalidade para leitura em bloco de materias do expediente
interlegis/sapl pull request #3618
Opened 2022-10-27 04:33 UTC by joaohortsenado

## Descrição
Incluida a possibilidade de leitura em bloco de materias do expediente, podendo selecionar materias ainda nao lidas, desde que estejam no expediente para tipo_votacao = 4 (LEITURA) e ainda nao tenham sido lidas.

## _Issue_ Relacionada
Ticket [#604548]

## Motivação e Contexto
Sugestao da comunidade, acatada por membros colaboradores.

## Como Isso Foi Testado?
Testado Localmente

## Capturas de Tela (se apropriado):

## Tipos de Mudanças

- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes)
- [ x] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes)
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes)

2022-10-27 20:38 UTC, edwardoliveira requested changes
Request for changes.

2022-10-27 21:03 UTC, edwardoliveira requested changes

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/sessao/urls.py
> +                               LeituraEmBlocoExpediente,
A LeituraEmBloco pode acontecer tanto na `OrdemDia` quanto `Expediente`. Teria que ter o correspondente ou renomear somente pra `LeituraEmBloco` se atender a ambos, que parece ser o caso.

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/sessao/urls.py
> +    url(r'^sessao/(?P<pk>\d+)/leitura_bloco_expediente$',
Mesmo comentário de cima.

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/sessao/views.py
> +class LeituraEmBlocoExpediente(PermissionRequiredForAppCrudMixin, ListView):
Renomear pra `LeituraEmBloco`

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/sessao/views.py
> +                                                retiradapauta=None, tipo_votacao=4, registroleitura__materia=None)
Colocar uma constante (`TIPO_LEITURA=4`) ao invés de usar número mágico. Eu acho que inclusive já existe a definição já existe.

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/sessao/views.py
> +            context['expediente'] = False
```suggestion
        context['expediente'] = True if self.expediente else False
```

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/sessao/views.py
> +            context['expediente'] = False
E se for uma `OrdemDia`?

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/sessao/views.py
> +                models = OrdemDia.objects.filter(id__in=request.POST.getlist('marcadas_4'))
nit: atribuir `reques.POST.getlist('marcadas_4')` a uma variável acima e referenciar aqui.

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/sessao/views.py
> +                models = ExpedienteMateria.objects.filter(id__in=request.POST.getlist('marcadas_4'))
Mesmo comentário acima.

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/sessao/views.py
> +            if models is None:
```suggestion
            if not models:
```

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/sessao/views.py
> +            else:
Como tem um return na linha 4424, não precisa desse `else`. Se ele entrar no if ele vai sair da função. Remover esse `else` e indentar o bloco abaixo, pois assim diminui a complexidade ciclomática do código e torna mais simples de ler.

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/sessao/views.py
> +                for m in models:
Muita calma nessa hora... :) Eles tão pedindo isso pra poder fazer leitura de 400 matérias ou mais! O **ideal** é tentar potencializar a quantidade de operações em lote o máximo que pudermos pra fazer o menor número possível de chamadas a BD. Neste sentido, eu sugiro que exploremos o uso de bulk_update, bulk_delete e bulk_create (um ou mais desses não está disponível no Django 2, se bem me lembro 😢). Considerando isso a gente pode fazer uma lógica mais ou menos assim:

DELETAR EM LOTE
```
materias = [m.materia for m in models]

RegistroLeitura.objects.filter(materia__in=materias, ...).delete()
```

Fazer o FOR pra criar os objetos novos

```
leituras = []
for m in models:
     obj = RegistroLeitura(ordem=m, materia=materia,
                           observacao=request.POST['observacao'],
                           user=self.request.user,
                           ip=get_client_ip(self.request)) 
                           // ou expediente=m Ah! E pode colocar tudo dentro do objeto, não precisa ser um por linha
     leituras.append(obj)
```

FORA do loop fazer um bulk_create: `RegistroLeituraz.objects.bulk_create(leituras)`

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/sessao/views.py
> +                            obj = RegistroLeitura()
```
     obj = RegistroLeitura(ordem=m, materia=materia,
                           observacao=request.POST['observacao'],
                           user=self.request.user,
                           ip=get_client_ip(self.request))
```

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/sessao/views.py
> +                        elif isinstance(m, OrdemDia):
Mesmo comentário de cima.

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/sessao/views.py
> +                        else:
Pergunta sincera: esse `else` é realmente necessário? Em qual situação ele entraria aqui? No meu entender o objeto pode somente ser `OrdemDia` ou `ExpedienteMateria`. E acho que também não seria `Tipo de Pauta` o que denomina esse objeto.

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/sessao/views.py
> +                    else:
Particularmente, acho esses `else` depois de `try-except` ou depois de `for loops` propícios a erros. Por que não colocar as linhas 4453 a 4455 após a linha 4446? O que se ganha definindo isso como um `else` a parte? Eu acho que esse `else` após try-except é válido quando precisamos limpar resources tipo conexão de BD, invalidação de cache, etc.

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/templates/sessao/leitura/leitura_bloco.html
> +                    {% if o.materia.numeracao_set.last %}
Precisa de tudo isso de informação? Digo, processo, número protocolo, tramitação, turno, etc? Eu acho que não. Lista a matéria (com link), autoria e tá bom! Não precisa recuperar tudo isso de informação nessa tela. A pessoa sabe o que deve inserir (eu acho, hahaha).

2022-10-27 21:03 UTC, edwardoliveira commented on sapl/templates/sessao/subnav.yaml
> +      url: leitura_bloco_expediente
Não teria que ter um respectivo pra ordem do dia?

2022-10-27 21:07 UTC, edwardoliveira commented on sapl/sessao/views.py
> +        if (obj.tipo_votacao != 4 and not exist_resultado and not exist_retirada) or \
Aproveitar e tirar o número mágico, substituindo por constante.

2022-10-27 21:08 UTC, edwardoliveira commented on sapl/sessao/views.py
> +                                                retiradapauta=None, tipo_votacao=4, registroleitura__materia=None)
`registroleitura__materia=None` eu **acho** que aqui seria `registroleitura__materia__isnull=True`, não?

2022-10-27 21:10 UTC, edwardoliveira commented on sapl/sessao/views.py
> +                        obj.ip = get_client_ip(self.request)
Esse bloco pode ser informado na hora que se cria o objeto.

2022-10-27 21:14 UTC, edwardoliveira commented on sapl/templates/sessao/leitura/leitura_bloco.html
> +        function checkAll(elem) {
Teria que ter um `uncheckAll` também?

2022-11-22 22:00 UTC, joaohortsenado commented on sapl/sessao/views.py
> +            context['expediente'] = False
adicionei a classe para ordem do dia.

2022-11-22 22:09 UTC, joaohortsenado commented on sapl/sessao/views.py
> +                                                retiradapauta=None, tipo_votacao=4, registroleitura__materia=None)
ambos funcionam, algum motivo especial pra usar um e nao o outro? 
![image](https://user-images.githubusercontent.com/100957576/203431086-bfdb88df-6123-41a4-9fd5-e90071e4f377.png)

2022-11-22 22:54 UTC, joaohortsenado commented on sapl/sessao/views.py
> +                            obj = RegistroLeitura()
Top!

2022-11-22 22:56 UTC, joaohortsenado commented on sapl/templates/sessao/leitura/leitura_bloco.html
> +                    {% if o.materia.numeracao_set.last %}
Eu basicamente copiei o que tinha de informacao na votacao... vou deixar, acho que eh valido.

2022-11-22 22:56 UTC, joaohortsenado commented on sapl/templates/sessao/subnav.yaml
> +      url: leitura_bloco_expediente
criado.

2022-11-22 22:58 UTC, joaohortsenado commented on sapl/templates/sessao/leitura/leitura_bloco.html
> +        function checkAll(elem) {
ao clicar novamente ele desmarca... na verdade o termo correto seria toggle

2022-12-06 13:26 UTC, edwardoliveira commented on sapl/sessao/views.py
> +                                                retiradapauta=None, tipo_votacao=4, registroleitura__materia=None)
A princípio não tem razão especial pra usar um ou outro, mas a maioria do nosso código usa `__isnull=True`.

2022-12-06 13:34 UTC, merged