fix: Corrige erro ao salvar partidos em bloco parlamentar
interlegis/sapl pull request #3625
Opened 2022-11-23 16:59 UTC by joaohortsenado

## Descrição
Corrige erro no salvamento de bancada parlamentar, persistindo no BD os partidos selecionados

## _Issue_ Relacionada
[Chamado #847863](https://suporte.interlegis.leg.br/scp/tickets.php?id=48741)

## Motivação e Contexto
Erro impeditivo

## Como Isso Foi Testado?
Localmente

## Tipos de Mudanças

- [ x] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes)
- [ ] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes)
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes)

## Checklist:

- [x ] Eu li o documento de Contribuição (**CONTRIBUTING**).
- [x ] Meu código segue o estilo de código deste projeto.
- [ ] Minha alteração requer uma alteração na documentação.
- [ ] Eu atualizei a documentação de acordo.
- [ ] Eu adicionei testes para cobrir minhas mudanças.
- [ x] Todos os testes novos e existentes passaram.

2022-11-23 18:51 UTC, LeandroJatai requested changes

2022-11-23 18:51 UTC, LeandroJatai commented on sapl/parlamentares/forms.py
> +        bloco.partidos.set(self.cleaned_data['partidos'])
Não funciona na inclusão...
```
   raise ValueError('"%r" needs to have a value for field "%s" before '
ValueError: "<Bloco: teste>" needs to have a value for field "id" before this many-to-many relationship can be used.
```

2022-11-23 18:51 UTC, LeandroJatai commented on sapl/parlamentares/forms.py
> +        bloco.partidos.set(self.cleaned_data['partidos'])
sugiro substituir o método save atual por este:
```
    @transaction.atomic
    def save(self, commit=False):

        id = self.instance.pk

        bloco = super(BlocoForm, self).save(commit=True)
        bloco.partidos.set(self.cleaned_data['partidos'])

        if not id:
            content_type = ContentType.objects.get_for_model(Bloco)
            object_id = bloco.pk
            tipo = TipoAutor.objects.get(content_type=content_type)
            Autor.objects.create(
                content_type=content_type,
                object_id=object_id,
                tipo=tipo,
                nome=bloco.nome
            )

        return bloco

```

2022-11-23 20:48 UTC, joaohortsenado commented on sapl/parlamentares/forms.py
> +        bloco.partidos.set(self.cleaned_data['partidos'])
Eu alterei a posicao do set do relacionamento, a sua sugestao incorreria no mesmo erro.

2022-12-01 15:29 UTC, edwardoliveira approved these changes
LGTM

2022-12-01 21:37 UTC, merged