No resultado da pesquisa de Matéria Legislativa, ordenar pela Sequencia Regimental ou Alfabética da Sigla
interlegis/sapl pull request #3673
Opened 2023-08-29 16:54 UTC by roberiorebeca

Com finalidade de facilitar a leitura da pesquisa de Matéria Legislativa, colocamos uma opção para definir qual a ordem se será pela Alfabética da Sigla, ou pela Sequencia Regimental que está informada no Cadastro de Tipo de Matéria.

## Descrição

- Para atender a esta necessidade eu inclui um campo ordem_sequencia_regimental no Models do arquivo sapl/base/models.py;
- Inclui a condição no arquivo sapl/materia/views.py para verificar qual a ordem definida nas configurações da aplicação;
- Fiz a rotina para criar o campo no banco de dados;
- No arquivos sapl/base/forms.py eu inclui o campo ordem_sequencia_regimental para que eles aparecesse na tela de configurações da aplicação;
- Incluir o campo ordem_sequencia_regimental no arquivo sapl/templates/base/layouts.yaml definido o tamanhos dos outros campos, para enquadrar na tela

## _Issue_ Relacionada

Foi aberto a issue https://github.com/interlegis/sapl/issues/3672

## Motivação e Contexto

Para facilitar a leitura da matéria legislativa pesquisada, na tela de Configurações da Aplicação, na parte que configura a Matéria Legislativo, inclui um campo para definir se a matéria vai obedecer a ordem da Sequencia Regimental. Caso deixe como NÃO, o sistema vai manter da forma que esta funcionando hoje, que é pela ordem Alfabética da Sigla.

## Como Isso Foi Testado?

Foi testado na minha maquina, rodando no WSL Ubuntu 18.04, subi a instancia do sistema, e fiz a configuração, e depois fiz a pesquisa da matéria legislativa.

## Capturas de Tela (se apropriado):

- **Imagem 1** _Cadastro do Tipo de Matéria Legislativa_
![image](https://github.com/interlegis/sapl/assets/14880091/9986b373-47ef-4099-bbcf-8fd9f0c9dfb9)

- **Imagem 2** _Configurações da Aplicação - Campo para definir a ordem da matéria pela sequencia regimental_
![image](https://github.com/interlegis/sapl/assets/14880091/f6ccd252-2f8f-4df1-9b33-c69cb0bab8e4)

- **Imagem 3** _Pesquisa de Matéria obedecendo a ordem Alfabética da Sigla_
![image](https://github.com/interlegis/sapl/assets/14880091/e1d500a2-0f71-4fd0-a681-48735bb18fd2)

- **Imagem 4** _Pesquisa de Matéria obedecendo a ordem da Sequencia Regimental_
![image](https://github.com/interlegis/sapl/assets/14880091/a998709c-7a56-4ea2-8829-0d2c5a9708fa)

## Tipos de Mudanças

- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes)
- [x] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes)
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes)

## Checklist:

- [x] Eu li o documento de Contribuição (**CONTRIBUTING**).
- [x] Meu código segue o estilo de código deste projeto.
- [x] Minha alteração requer uma alteração na documentação.
- [ ] Eu atualizei a documentação de acordo.
- [ ] Eu adicionei testes para cobrir minhas mudanças.
- [ ] Todos os testes novos e existentes passaram.

2023-08-31 02:28 UTC, edwardoliveira requested changes

2023-08-31 02:28 UTC, edwardoliveira commented on sapl/base/models.py
> +    ordem_sequencia_regimental = models.BooleanField(
**Se a intenção é mudar a ordenação de TODAS as pesquisas de matéria, o melhor seria criar um campo de select com a opção original e a nova, tendo a mais antiga como default, e não um campo boolean. Daí o nome deste atributo no model AppConfig pode ser simplesmente `ordenacao_pesquisa_materia`.**

2023-08-31 02:28 UTC, edwardoliveira commented on sapl/materia/views.py
> +                qs = qs.order_by('-ano', 'tipo__sigla', '-numero')
```suggestion
            if BaseAppConfig.attr('ordem_sequencia_regimental'):
                args = ['-ano', 'tipo__sequencia_regimental', '-numero']
            else:
                args = ['-ano', 'tipo__sigla', '-numero']
            qs = qs.order_by(*args)
```

2023-08-31 02:28 UTC, edwardoliveira commented on sapl/base/models.py
> +    ordem_sequencia_regimental = models.BooleanField(
Quando se adiciona um campo no model deve-se executar o comando `./manage.py makemigrations <app_name>` para gerar os arquivos de alteração no BD, e incluí-los nesse PR.

2023-08-31 10:43 UTC, roberiorebeca commented on sapl/base/models.py
> +    ordem_sequencia_regimental = models.BooleanField(
Olá Edward Oliveira.

Certo. Vou mudar então, e criar um campo pra informar que a ordem será pelo Tipo (Sigla) ou Sequencia Regimental, e colocar o Tipo como padrão.

2023-08-31 10:45 UTC, roberiorebeca commented on sapl/base/models.py
> +    ordem_sequencia_regimental = models.BooleanField(
Certo. Vou me atentar a este detalhe.

Eu rodei aqui mas por ser o primeiro PR que envio, pensei que fosse rotina, quando baixar o código pra testar, rodar o makemigrations. Mas vou subir no proximo commit.

2023-09-02 13:55 UTC, edwardoliveira requested changes

2023-09-02 13:55 UTC, edwardoliveira commented on sapl/base/models.py
> +    ('A', _('Alfabetica pela Sigla')),
```suggestion
    ('A', _('Alfabética por sigla')),
```

Nit: poderia trocar o caracter de 'A' pra 'S', por favor?

2023-09-02 13:55 UTC, edwardoliveira commented on sapl/base/models.py
> +    ('R', _('Sequencia Regimental')),
```suggestion
    ('R', _('Sequência Regimental')),
```

2023-09-02 13:55 UTC, edwardoliveira commented on sapl/base/models.py
> +            'Ordem de Pesquisa da Matéria?'),
```suggestion
            'Ordenação de Pesquisa da Matéria?'),
```

2023-09-02 13:55 UTC, edwardoliveira commented on sapl/materia/views.py
> +                qs = qs.order_by('-ano', 'tipo__sigla', '-numero')
```suggestion
            args = ['-ano', 'tipo__sequencia_regimental', '-numero'] \ 
                   if BaseAppConfig.attr('ordenacao_pesquisa_materia') == 'R' else ['-ano', 'tipo__sigla', '-numero']
           qs = qs.order_by(*args)
```

2023-09-02 13:55 UTC, edwardoliveira commented on sapl/base/migrations/0058_appconfig_ordem_sequencia_regimental.py
> +# Generated by Django 2.2.28 on 2023-08-29 13:47
Essa sequência de migrations (58, 59, 60, 61) para a mesma coluna no mesmo PR não são o desejável. Eu sugiro que vc:

1. apague todas as migrations geradas;
2. remova a coluna recém criada da tabela;
3. rode o `./manage.py makemigrations` de novo

Isso vai criar somente uma migration com o tipo correto, que você pode adicionar a este PR.

2023-09-30 20:04 UTC, edwardoliveira commented
Oi @roberiorebeca, 

Mil perdões pela demora, eu entrei de férias por um mês, e logo que voltei de férias adoeci por duas semanas. :( Mudanças recentes em pauta de sessão estão dando conflito com teu PR. Você poderia consertar e submeter as mudanças neste PR (não precisa abrir outro!) que eu reviso e faço o merge, por favor? Obrigado!

2023-09-30 22:07 UTC, merged